Unstaged changes after reset:
M	packages/compile/package.json
M	packages/compile/src/compile.js
M	packages/compile/tests/compile.spec.js
M	packages/democracy.js/departures/interface.js
M	packages/democracy.js/departures/multiLib.js
M	packages/democracy.js/index.js
M	packages/democracy.js/package-lock.json
M	packages/democracy.js/package.json
M	packages/democracy.js/src/deploy.js
M	packages/democracy.js/src/lib.js
D	packages/democracy.js/src/link.js
M	packages/democracy.js/tests/link.spec.js
M	packages/democracy.js/tests/round-trip-use-library.js
M	packages/keys/package.json
M	packages/keys/src/keys.js
M	packages/linker/linker.js
M	packages/utils/src/utils.js
M	packages/utils/tests/remote.spec.js
M	packages/webify/package.json
